<a href="https://colab.research.google.com/github/bttrung/secure-private-ai-scholarship/blob/master/1_Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install torch torchvision

In [0]:
import torch

In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [0]:
# Now, make our labels from our data and true weights

y = activation(torch.sum(features * weights) + bias)
y = activation((features * weights).sum() + bias)

In [0]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [10]:
y

tensor([[0.1595]])

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [12]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [13]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.99761649, 0.58439415, 0.11673524],
       [0.10166338, 0.15472068, 0.12920687],
       [0.19888063, 0.61424961, 0.25887318],
       [0.11710813, 0.51034856, 0.51402042]])

In [14]:
b = torch.from_numpy(a)
b

tensor([[0.9976, 0.5844, 0.1167],
        [0.1017, 0.1547, 0.1292],
        [0.1989, 0.6142, 0.2589],
        [0.1171, 0.5103, 0.5140]], dtype=torch.float64)

In [15]:
b.numpy()

array([[0.99761649, 0.58439415, 0.11673524],
       [0.10166338, 0.15472068, 0.12920687],
       [0.19888063, 0.61424961, 0.25887318],
       [0.11710813, 0.51034856, 0.51402042]])

In [16]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.9952, 1.1688, 0.2335],
        [0.2033, 0.3094, 0.2584],
        [0.3978, 1.2285, 0.5177],
        [0.2342, 1.0207, 1.0280]], dtype=torch.float64)